# Generated by Django 3.1.5 on 2021-03-20 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20210319_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='pat_profile',
            name='firstname',
            field=models.CharField(default='firstname', max_length=100),
        ),
        migrations.AddField(
            model_name='pat_profile',
            name='lastname',
            field=models.CharField(default='lastname', max_length=100),
        ),
        migrations.AlterField(
            model_name='pat_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pat_Profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
