# Generated by Django 3.1.5 on 2021-03-20 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210320_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='pat_profile',
            name='address',
            field=models.CharField(default='address', max_length=300),
        ),
        migrations.AddField(
            model_name='pat_profile',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pat_profile',
            name='city',
            field=models.CharField(default='city', max_length=100),
        ),
        migrations.AddField(
            model_name='pat_profile',
            name='country',
            field=models.CharField(default='country', max_length=100),
        ),
        migrations.AddField(
            model_name='pat_profile',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='pat_profile',
            name='postalcode',
            field=models.IntegerField(default=0),
        ),
    ]
