# Generated by Django 3.1.5 on 2021-03-28 10:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0003_auto_20210328_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('firstname', models.CharField(default='firstname', max_length=100)),
                ('lastname', models.CharField(default='lastname', max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('address', models.CharField(default='address', max_length=300)),
                ('city', models.CharField(default='city', max_length=100)),
                ('country', models.CharField(default='country', max_length=100)),
                ('postalcode', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
