# Generated by Django 3.1.5 on 2021-03-28 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hospital.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0006_auto_20210328_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.ForeignKey(default=hospital.models.defaultuser, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
