# Generated by Django 3.1.5 on 2021-04-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_auto_20210414_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctorId',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patientId',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
