# Generated by Django 3.1.5 on 2021-04-19 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0017_auto_20210415_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctorName',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patientName',
        ),
    ]
