# Generated by Django 3.1.5 on 2021-04-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20210419_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='link',
            field=models.TextField(null=True),
        ),
    ]
