# Generated by Django 3.1.5 on 2021-04-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_auto_20210424_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatBasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('height', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PatDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('disease', models.CharField(default='somedisease', max_length=100)),
            ],
        ),
    ]
