# Generated by Django 3.1.5 on 2021-04-25 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_patbasicinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patbasicinfo',
            name='age',
        ),
    ]
