# Generated by Django 3.1.5 on 2021-04-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_patbasicinfo_patdisease'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('height', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('diseases', models.CharField(default='somediseases', max_length=2000)),
                ('medicines', models.CharField(default='somemedicines', max_length=2000)),
                ('ts', models.CharField(default='treatments/surgery', max_length=2000)),
            ],
        ),
    ]
