# Generated by Django 3.1.5 on 2021-04-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_pathealth'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatAdmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('doctorId', models.PositiveIntegerField(null=True)),
                ('admitDate', models.DateField()),
                ('description', models.TextField()),
                ('dischargeDate', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='PatBasicInfo',
        ),
        migrations.DeleteModel(
            name='PatDisease',
        ),
    ]
