# Generated by Django 3.1.5 on 2021-04-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_remove_patbasicinfo_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('disease', models.CharField(default='somedisease', max_length=100)),
            ],
        ),
    ]
