# Generated by Django 3.1.5 on 2021-04-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_auto_20210429_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathealth',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
